// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetsAction
    {
        public AssetsAction()
        {
            AssetTransactions = new HashSet<AssetTransactions>();
        }

        public int AsstActionId { get; set; }
        public string AsstActionName { get; set; }

        public virtual ICollection<AssetTransactions> AssetTransactions { get; set; }
    }
}