// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetTransactions
    {
        /// <summary>
        /// Asset Transaction ID
        /// </summary>
        public int TransactionId { get; set; }
        public int? AssetId { get; set; }
        /// <summary>
        /// Asset Actions { Add Asset, Transfer Asset, Delete Asset }
        /// </summary>
        public int? AsstActionId { get; set; }
        public DateTime? TranDate { get; set; }
        /// <summary>
        /// Vehicle or Heavy Equipment ID
        /// </summary>
        public int? VehPropId { get; set; }
        /// <summary>
        /// Comm. Court Date
        /// </summary>
        public DateTime? CommCourtDate { get; set; }
        /// <summary>
        /// Agenda Item
        /// </summary>
        public string AgendaItem { get; set; }
        /// <summary>
        /// From this department ID
        /// </summary>
        public int? OldDep { get; set; }
        /// <summary>
        /// To new Department ID 
        /// </summary>
        public int? NewDep { get; set; }
        public string Reason { get; set; }
        public int? UserId { get; set; }

        public virtual Assets Asset { get; set; }
        public virtual AssetsAction AsstAction { get; set; }
        public virtual Vehicles VehProp { get; set; }
    }
}