// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetInsurances
    {
        /// <summary>
        /// Insurance ID
        /// </summary>
        public int InsuranceId { get; set; }
        /// <summary>
        /// Type of asset
        /// </summary>
        public int AssetId { get; set; }
        /// <summary>
        /// Type of insurance form
        /// </summary>
        public int InsActionId { get; set; }
        /// <summary>
        /// Vehicle or Heavy Equipment ID
        /// </summary>
        public int VehPropId { get; set; }
        /// <summary>
        /// Insurance Date
        /// </summary>
        public DateTime? InsDate { get; set; }
        /// <summary>
        /// Policy 
        /// </summary>
        public int InsTypeId { get; set; }
        /// <summary>
        /// Asset Coverage
        /// </summary>
        public decimal? AssetCoverage { get; set; }
        /// <summary>
        /// Contents Coverage
        /// </summary>
        public decimal? ContentsCoverage { get; set; }
        public string Reason { get; set; }
        public int? Contact1 { get; set; }
        public DateTime? Date1 { get; set; }
        public int? Contact2 { get; set; }
        public DateTime? Date2 { get; set; }
        public int? Contact3 { get; set; }
        public DateTime? Date3 { get; set; }
        public int? UserId { get; set; }

        public virtual Assets Asset { get; set; }
        public virtual InsuranceActions InsAction { get; set; }
        public virtual InsuranceTypes InsType { get; set; }
        public virtual Vehicles VehProp { get; set; }
    }
}