// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetStatus
    {
        public AssetStatus()
        {
            Properties = new HashSet<Properties>();
            Vehicles = new HashSet<Vehicles>();
        }

        public int StatusId { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<Properties> Properties { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}