// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetAcquisition
    {
        public AssetAcquisition()
        {
            Vehicles = new HashSet<Vehicles>();
        }

        public int AcqId { get; set; }
        public string AcqName { get; set; }

        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}