// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class AssetActionHistory
    {
        public int ChangeId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int AsstActionId { get; set; }
        public int TransactionId { get; set; }
        public DateTime ChangeDate { get; set; }
    }
}