// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Assets
    {
        public Assets()
        {
            AssetInsurances = new HashSet<AssetInsurances>();
            AssetTransactions = new HashSet<AssetTransactions>();
            AssetTypes = new HashSet<AssetTypes>();
            Properties = new HashSet<Properties>();
            Vehicles = new HashSet<Vehicles>();
        }

        public int AssetId { get; set; }
        public string AssetName { get; set; }

        public virtual ICollection<AssetInsurances> AssetInsurances { get; set; }
        public virtual ICollection<AssetTransactions> AssetTransactions { get; set; }
        public virtual ICollection<AssetTypes> AssetTypes { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}