// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Departments
    {
        public Departments()
        {
            DepLocations = new HashSet<DepLocations>();
            Properties = new HashSet<Properties>();
            Users = new HashSet<Users>();
            Vehicles = new HashSet<Vehicles>();
        }

        public int DepId { get; set; }
        public string DepNum { get; set; }
        public string DepName { get; set; }

        public virtual ICollection<DepLocations> DepLocations { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}