// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class InsuranceActions
    {
        public InsuranceActions()
        {
            AssetInsurances = new HashSet<AssetInsurances>();
        }

        /// <summary>
        /// Type of insurance form
        /// </summary>
        public int InsActionId { get; set; }
        public string InsActionName { get; set; }

        public virtual ICollection<AssetInsurances> AssetInsurances { get; set; }
    }
}