// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class InsuranceTypes
    {
        public InsuranceTypes()
        {
            AssetInsurances = new HashSet<AssetInsurances>();
        }

        public int InsTypeId { get; set; }
        public string InsName { get; set; }
        public string InsDesc { get; set; }

        public virtual ICollection<AssetInsurances> AssetInsurances { get; set; }
    }
}