// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Items
    {
        public Items()
        {
            VehicleItems = new HashSet<VehicleItems>();
        }

        public int ItemId { get; set; }
        public string ItemName { get; set; }

        public virtual ICollection<VehicleItems> VehicleItems { get; set; }
    }
}