// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class PropertyCons
    {
        public PropertyCons()
        {
            Properties = new HashSet<Properties>();
        }

        public int ConstructionId { get; set; }
        public string ConstDesc { get; set; }

        public virtual ICollection<Properties> Properties { get; set; }
    }
}