// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Properties
    {
        public int PropertyId { get; set; }
        public int AssetId { get; set; }
        public int DepId { get; set; }
        public int? LocationId { get; set; }
        public int UserId { get; set; }
        public string FacilityName { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string RoofType { get; set; }
        public int? NumStories { get; set; }
        public int? SqFtAcreage { get; set; }
        /// <summary>
        /// Year Built
        /// </summary>
        public int? YearId { get; set; }
        /// <summary>
        /// Sprinklers [Y/N]
        /// </summary>
        public int? Sprinklers { get; set; }
        /// <summary>
        /// Electronic Equipment [Y/N]
        /// </summary>
        public int? ElectronicEquip { get; set; }
        public int? NumFloors { get; set; }
        public int? ConstructionId { get; set; }
        public string Occupancy { get; set; }
        public string Comments { get; set; }
        public int? SatusId { get; set; }

        public virtual Assets Asset { get; set; }
        public virtual PropertyCons Construction { get; set; }
        public virtual Departments Dep { get; set; }
        public virtual DepLocations Location { get; set; }
        public virtual AssetStatus Satus { get; set; }
        public virtual Users User { get; set; }
    }
}