// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Users
    {
        public Users()
        {
            Properties = new HashSet<Properties>();
            UserRoles = new HashSet<UserRoles>();
            Vehicles = new HashSet<Vehicles>();
        }

        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public int? DepId { get; set; }
        public bool? Active { get; set; }
        public string Extension { get; set; }

        public virtual Departments Dep { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}