// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class VehicleItems
    {
        public int VeItemId { get; set; }
        public int? VehicleId { get; set; }
        public int? ItemId { get; set; }
        public decimal? ItemCost { get; set; }

        public virtual Items Item { get; set; }
        public virtual Vehicles Vehicle { get; set; }
    }
}