// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class VehicleModels
    {
        public VehicleModels()
        {
            Vehicles = new HashSet<Vehicles>();
        }

        public int ModelId { get; set; }
        public int? MakeId { get; set; }
        public string ModelName { get; set; }

        public virtual VehicleMakes Make { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}