// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace i_App.Data.models
{
    public partial class Vehicles
    {
        public Vehicles()
        {
            AssetInsurances = new HashSet<AssetInsurances>();
            AssetTransactions = new HashSet<AssetTransactions>();
            VehicleItems = new HashSet<VehicleItems>();
        }

        public int VehicleId { get; set; }
        public int? DepId { get; set; }
        public int? LocationId { get; set; }
        public int? UserId { get; set; }
        public int? AcqId { get; set; }
        /// <summary>
        /// Acquisition Date
        /// </summary>
        public DateTime? AcqDate { get; set; }
        /// <summary>
        /// Received Date
        /// </summary>
        public DateTime? RcvdDate { get; set; }
        /// <summary>
        /// Estimate Arrival Date
        /// </summary>
        public DateTime? EstimateDate { get; set; }
        public string TitleName { get; set; }
        public int? AssetId { get; set; }
        public int? AssetTypeId { get; set; }
        public int? MakeId { get; set; }
        public int? ModelId { get; set; }
        public int? YearId { get; set; }
        public int? Mileage { get; set; }
        public string VinSerialNumber { get; set; }
        public string LicenseTag { get; set; }
        public string CountyAsset { get; set; }
        public decimal? BookValue { get; set; }
        public string PoNumber { get; set; }
        public int? AssetAge { get; set; }
        public int? StatusId { get; set; }
        public string Notes { get; set; }
        public int? ReqNum { get; set; }

        public virtual AssetAcquisition Acq { get; set; }
        public virtual Assets Asset { get; set; }
        public virtual AssetTypes AssetType { get; set; }
        public virtual Departments Dep { get; set; }
        public virtual DepLocations Location { get; set; }
        public virtual VehicleMakes Make { get; set; }
        public virtual VehicleModels Model { get; set; }
        public virtual AssetStatus Status { get; set; }
        public virtual Users User { get; set; }
        public virtual AssetYears Year { get; set; }
        public virtual ICollection<AssetInsurances> AssetInsurances { get; set; }
        public virtual ICollection<AssetTransactions> AssetTransactions { get; set; }
        public virtual ICollection<VehicleItems> VehicleItems { get; set; }
    }
}